"""delete column

Revision ID: 72340dc1fa24
Revises: 9b6a6007f222
Create Date: 2022-02-14 12:51:38.150615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72340dc1fa24'
down_revision = '9b6a6007f222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'number_of_views')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('number_of_views', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
